services:
  web-share:
    container_name: web-share
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - VITE_SERVER_URL=http://localhost:3001
    networks:
      - net
    restart: unless-stopped

networks:
  net: